[build]
  # Install dependencies and build the app
  command = "cd web && npm install && npm run build"
  publish = "web/build"

[build.environment]
  NODE_ENV = "production"
  
[[redirects]]
  from = "/api/hello"
  to = "/api-mock/hello.txt"
  status = 200